name = "dilmahtea-me-stripe-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-06-26"
main = "./dist/worker.js"
workers_dev = false
build = { command = "node build" }
routes = [
    { pattern = "pay-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "CROWDFUNDING", id = "c971dd86589647799fb64dde47563fac" }
]
services = [
    { binding = "EMAIL", service = "dilmahtea-me-email", environment = "production" },
    { binding = "BASEROW", service = "dilmahtea-me-baserow", environment = "production" }
]

[env.development]
name = "dilmahtea-me-stripe-webhook-dev"
build = { command = "node build --dev" }
routes = [
    { pattern = "dev.pay-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "CROWDFUNDING", id = "c971dd86589647799fb64dde47563fac" }
]
services = [
    { binding = "EMAIL", service = "dilmahtea-me-email-dev", environment = "production" },
    { binding = "BASEROW", service = "dilmahtea-me-baserow-dev", environment = "production" }
]
