name = "dilmahtea-me-stripe-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
workers_dev = true
compatibility_date = "2022-06-26"
main = "./dist/worker.js"

[[kv_namespaces]]
binding = "CROWDFUNDING"
preview_id = "178f6309789141938fd626f93f508f22"
id = "c971dd86589647799fb64dde47563fac"

[[services]]
binding = "EMAIL"
service = "dilmahtea-me-email"
environment = "production"

[[services]]
binding = "BASEROW"
service = "dilmahtea-me-baserow"
environment = "production"

[build]
command = "npm run build"