name = "dilmahtea-me-email"
main = "./index.js"
account_id = "f0f636c746c8673c3905e9104b385251"
workers_dev = true
compatibility_date = "2022-06-08"

[[kv_namespaces]]
binding = "CROWDFUNDING_EMAIL"
id = "083cbf62d5ac4918923b7f30d8f40b31"
