name = "dilmahtea-me-baserow"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = false
logpush = true
placement = { mode = "smart" }
routes = [
    { pattern = "baserow.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "CROWDFUNDINGS", id = "c971dd86589647799fb64dde47563fac" },
    { binding = "ECOMMERCE_PAYMENTS", id = "5086c43e26a14fa3a177ea876f514a8f" }
]

[env.development]
name = "dilmahtea-me-baserow-dev"
routes = [
    { pattern = "dev.baserow.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "CROWDFUNDINGS", id = "bce59b3e55474063abce8ef8f5d755e7" },
    { binding = "ECOMMERCE_PAYMENTS", id = "acd54db867fe4fa18351d3b89a00c05a" }
]

# secrets
# BASEROW_TOKEN
# BASEROW_CROWDFUNDING_TABLE_ID
# BASEROW_PAYMENT_RECORDS_TABLE_ID