name = "dilmahtea-me-strapi-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.js"
workers_dev = false
logpush = true
placement = { mode = "smart" }
routes = [
    { pattern = "cms-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [{ binding = "MAILS", id = "51f5be62eaf64aa8a9c69bccb81d396e" }]

[env.development]
name = "dilmahtea-me-strapi-webhook-dev"
routes = [
    { pattern = "dev.cms-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [{ binding = "MAILS", id = "7001794de1f245c0b37792b9215c1acf" }]

# secrets
# CMS_ACCESS_TOKEN
# CMS_GRAPHQL_ENDPOINT
