name = "dilmahtea-me-stripe"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.js"
workers_dev = false
logpush = true
placement = { mode = "smart" }
vars = { ORIGIN = "https://dilmahtea.me" }
routes = [
    { pattern = "pay.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "CROWDFUNDINGS", id = "c971dd86589647799fb64dde47563fac" },
    { binding = "ECOMMERCE_PAYMENTS", id = "5086c43e26a14fa3a177ea876f514a8f" }
]
d1_databases = [
    { binding = "USERS", database_name = "users", database_id = "74a1dc02-0705-44fb-b009-fb2fe974e098" }
]

[env.development]
name = "dilmahtea-me-stripe-dev"
vars = { ORIGIN = "https://dev.dilmahtea-me.pages.dev", CF_PAGES_DOMAIN = "https://*.dilmahtea-me.pages.dev" }
routes = [
    { pattern = "dev.pay.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "CROWDFUNDINGS", id = "bce59b3e55474063abce8ef8f5d755e7" },
    { binding = "ECOMMERCE_PAYMENTS", id = "acd54db867fe4fa18351d3b89a00c05a" }
]
d1_databases = [
    { binding = "USERS", database_name = "users_dev", database_id = "076751ed-7610-4965-b72d-e9d619227957" }
]

# secrets
# STRIPE_SECRET_KEY
# BASEROW_TOKEN
# BASEROW_CROWDFUNDING_TABLE_ID
# BASEROW_PAYMENT_RECORDS_TABLE_ID