export interface ENV {
  // ENVIRONMENTAl VARIABLES
  ENVIRONMENT: "PRODUCTION" | "DEVELOPMENT";
  PAYMENT_CONDITION: "VB";
  EMAIL_WORKER_URL: string;
  EXACT_ACCOUNT_WORKER_URL: string;

  // KV
  MAILS: KVNamespace;
  EXACT_TOKENS: KVNamespace;
  CROWDFUNDINGS: KVNamespace;
  ECOMMERCE_PAYMENTS: KVNamespace;
  WORKER_CONTEXTS: KVNamespace;

  // D1
  USERS: D1Database;

  // BASEROW
  BASEROW_TOKEN: string;
  BASEROW_CROWDFUNDING_TABLE_ID: string;
  BASEROW_PAYMENT_RECORDS_TABLE_ID: string;

  // DKIM MAILCHANNELS
  DKIM_PRIVATE_KEY: string;

  // STRAPI
  STRAPI_ACCESS_TOKEN: string;
  STRAPI_GRAPHQL_ENDPOINT: string;

  // DIMASS
  DIMASS_API_KEY: string;
  DIMASS_API_URL: string;
  DIMASS_API_SECRET: string;

  // STRIPE
  STRIPE_SECRET_KEY: string;
  STRIPE_SIGNING_SECRET_KEY: string;

  // SERVICES
  EMAIL: Fetcher;
  EXACT_ACCOUNT: Fetcher;

  // EXACT
  EXACT_API_ENDPOINT: string;

  // SECURE WORKERS
  CF_SECURE_WORKER_TOKEN: string;
}
