export interface ENV {
  // ENVIRONMENTAl VARIABLES
  ENVIRONMENT: "PRODUCTION" | "DEVELOPMENT";
  PAYMENT_CONDITION: "VB";

  // KV
  MAILS: KVNamespace;
  EXACT_TOKENS: KVNamespace;
  CROWDFUNDINGS: KVNamespace;
  ECOMMERCE_PAYMENTS: KVNamespace;
  WORKER_CONTEXTS: KVNamespace;

  // BASEROW
  BASEROW_TOKEN: string;
  BASEROW_CROWDFUNDING_TABLE_ID: string;
  BASEROW_PAYMENT_RECORDS_TABLE_ID: string;

  // DKIM MAILCHANNELS
  DKIM_PRIVATE_KEY: string;

  // STRAPI
  STRAPI_ACCESS_TOKEN: string;
  STRAPI_GRAPHQL_ENDPOINT: string;

  // DIMASS
  DIMASS_API_KEY: string;
  DIMASS_API_URL: string;
  DIMASS_API_SECRET: string;

  // EXACT
  EXACT_API_ENDPOINT: string;

  // STRIPE
  STRIPE_SECRET_KEY: string;
  STRIPE_SIGNING_SECRET_KEY: string;
}
