name = "dilmahtea-me-exact-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = false
logpush = true
placement = { mode = "smart" }
routes = [
    { pattern = "exact-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [{ binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" }]
services = [{ binding = "RETRY_WORKERS", service = "dilmahtea-me-retry-workers" }]

[env.development]
name = "dilmahtea-me-exact-webhook-dev"
routes = [
    { pattern = "dev.exact-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [{ binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" }]
services = [{ binding = "RETRY_WORKERS", service = "dilmahtea-me-retry-workers" }]

# secrets
# STRAPI_WEBHOOK_SECRET
# STRAPI_ACCESS_TOKEN
# STRAPI_GRAPHQL_ENDPOINT
