name = "dilmahtea-me-retry-workers"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = false
logpush = true
triggers = { crons = ["*/1 * * * *"]}
kv_namespaces = [{ binding = "WORKER_REQUESTS", id = "49c94598e0654db8a2064d4f1874ff26" }]
d1_databases = [
    { binding = "USERS", database_name = "users", database_id = "74a1dc02-0705-44fb-b009-fb2fe974e098" }
]
services = [{ binding = "EMAIL", service = "dilmahtea-me-email" }]

[vars]
EMAIL_WORKER_URL = "https://email.scripts.dilmahtea.me"

# secrets
# DKIM_PRIVATE_KEY
# MATRIX_ROOM_ID
# MATRIX_BOT_ACCESS_TOKEN
# CF_SECURE_WORKER_TOKEN