name = "dilmahtea-me-baserow-stats"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.js"
workers_dev = true
logpush=true

routes = [
    { pattern = "crowdfunding-stats.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "BASEROW_STATS", id = "abc253e545bf4c3ebdc1b8577e88967e" }
]

[env.development]
name = "dilmahtea-me-baserow-stats-dev"
routes = [
    { pattern = "dev.crowdfunding-stats.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "BASEROW_STATS", id = "b079d7c054bc4bc3b4cbfdb244c5aa29" }
]
