name = "dilmahtea-me-stripe"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-06-21"
main = "./dist/worker.js"
workers_dev = false
build = { command = "node build" }
routes = [
    { pattern = "pay.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "CROWDFUNDING", id = "c971dd86589647799fb64dde47563fac" }
]

[env.development]
name = "dilmahtea-me-stripe-dev"
build = { command = "node build --dev" }
routes = [
    { pattern = "dev.pay.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "CROWDFUNDING", id = "c971dd86589647799fb64dde47563fac" }
]
