export interface ENV {
  // ENVIRONMENTAl VARIABLES
  ENVIRONMENT: "PRODUCTION" | "DEVELOPMENT";
  JOURNAL_CODE: "VER";

  // KV
  EXACT_TOKENS: KVNamespace;
  EXACT_LAYOUTS: KVNamespace;
  WORKER_CONTEXTS: KVNamespace;

  // D1
  USERS: D1Database;

  // EXACT
  EXACT_API_ENDPOINT: string;

  // DIMASS
  DIMASS_API_KEY: string;
  DIMASS_API_SECRET: string;
  DIMASS_API_ENDPOINT: string;
  DIMASS_WEBHOOK_SECRET: string;

  // STRAPI
  STRAPI_ACCESS_TOKEN: string;
  STRAPI_GRAPHQL_ENDPOINT: string;
}
