name = "dilmahtea-me-stripe-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = false
logpush = true
placement = { mode = "smart" }
vars = { ENVIRONMENT = "PRODUCTION", PAYMENT_CONDITION = "VB" }
routes = [
    { pattern = "pay-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "MAILS", id = "51f5be62eaf64aa8a9c69bccb81d396e" },
    { binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" },
    { binding = "CROWDFUNDINGS", id = "c971dd86589647799fb64dde47563fac" },
    { binding = "ECOMMERCE_PAYMENTS", id = "5086c43e26a14fa3a177ea876f514a8f" },
    { binding = "WORKER_CONTEXTS", id = "bf39422efbc34bd58d3c3e064660474f" }
]
d1_databases = [
    { binding = "USERS", database_name = "users", database_id = "74a1dc02-0705-44fb-b009-fb2fe974e098" }
]
services = [{ binding = "RETRY_WORKERS", service = "dilmahtea-me-retry-workers" }]

[env.development]
name = "dilmahtea-me-stripe-webhook-dev"
vars = { ENVIRONMENT = "DEVELOPMENT", PAYMENT_CONDITION = "VB" }
routes = [
    { pattern = "dev.pay-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "MAILS", id = "7001794de1f245c0b37792b9215c1acf" },
    { binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" },
    { binding = "CROWDFUNDINGS", id = "bce59b3e55474063abce8ef8f5d755e7" },
    { binding = "ECOMMERCE_PAYMENTS", id = "acd54db867fe4fa18351d3b89a00c05a" },
    { binding = "WORKER_CONTEXTS", id = "710872f91ae946d987a38af244352718" }
]
d1_databases = [
    { binding = "USERS", database_name = "users_dev", database_id = "076751ed-7610-4965-b72d-e9d619227957" }
]
services = [{ binding = "RETRY_WORKERS", service = "dilmahtea-me-retry-workers" }]

# secrets
# BASEROW_TOKEN
# BASEROW_CROWDFUNDING_TABLE_ID
# BASEROW_PAYMENT_RECORDS_TABLE_ID
# DKIM_PRIVATE_KEY
# STRAPI_ACCESS_TOKEN
# STRAPI_GRAPHQL_ENDPOINT
# DIMASS_API_KEY
# DIMASS_API_URL
# DIMASS_API_SECRET
# EXACT_API_ENDPOINT
# STRIPE_SECRET_KEY
# STRIPE_SIGNING_SECRET_KEY
