name = "dilmahtea-me-stripe-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.js"
workers_dev = false
logpush = true
placement = { mode = "smart" }
vars = { ENVIRONMENT = "PRODUCTION", PAYMENT_CONDITION = "VB" }
routes = [
    { pattern = "pay-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "MAILS", id = "51f5be62eaf64aa8a9c69bccb81d396e" },
    { binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" },
    { binding = "CROWDFUNDINGS", id = "c971dd86589647799fb64dde47563fac" },
    { binding = "ECOMMERCE_PAYMENTS", id = "5086c43e26a14fa3a177ea876f514a8f" }
]

[env.development]
name = "dilmahtea-me-stripe-webhook-dev"
vars = { ENVIRONMENT = "DEVELOPMENT", PAYMENT_CONDITION = "IN" }
routes = [
    { pattern = "dev.pay-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "MAILS", id = "7001794de1f245c0b37792b9215c1acf" },
    { binding = "EXACT_TOKENS", id = "194d0b00ac24422bb728e326bb43480c" },
    { binding = "CROWDFUNDINGS", id = "bce59b3e55474063abce8ef8f5d755e7" },
    { binding = "ECOMMERCE_PAYMENTS", id = "acd54db867fe4fa18351d3b89a00c05a" }
]

# secrets
# BASEROW_TOKEN
# DKIM_PRIVATE_KEY
# CMS_ACCESS_TOKEN
# CMS_GRAPHQL_ENDPOINT
# DIMASS_API_KEY
# DIMASS_API_URL
# DIMASS_API_SECRET
# EXACT_API_ENDPOINT
# STRIPE_DEVELOPMENT_SECRET_KEY
# STRIPE_DEVELOPMENT_SIGNING_SECRET_KEY
# STRIPE_PRODUCTION_SECRET_KEY
# STRIPE_PRODUCTION_SIGNING_SECRET_KEY
