name = "dilmahtea-me-stripe-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.js"
workers_dev = false
routes = [
    { pattern = "pay-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "MAILS", id = "51f5be62eaf64aa8a9c69bccb81d396e" },
    { binding = "CROWDFUNDINGS", id = "c971dd86589647799fb64dde47563fac" },
    { binding = "ECOMMERCE_PAYMENTS", id = "5086c43e26a14fa3a177ea876f514a8f" }
]

[env.development]
name = "dilmahtea-me-stripe-webhook-dev"
routes = [
    { pattern = "dev.pay-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [
    { binding = "MAILS", id = "51f5be62eaf64aa8a9c69bccb81d396e" },
    { binding = "CROWDFUNDINGS", id = "c971dd86589647799fb64dde47563fac" },
    { binding = "ECOMMERCE_PAYMENTS", id = "5086c43e26a14fa3a177ea876f514a8f" }
]
