name = "dilmahtea-me-dimass"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = true
logpush=true
routes = [
    { pattern = "dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]

[env.development]
name = "dilmahtea-me-dimass-dev"
routes = [
    { pattern = "dev.dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]

# secrets
# STRAPI_APIKEY
# STRAPI_API_ENDPOINT
# STRAPI_GRAPHQL_ENDPOINT
# DIMASS_APIKEY
# DIMASS_SECRET
# DIMASS_API_ENDPOINT
# DIMASS_WEBHOOK_SECRET
