name = "dilmahtea-me-dimass"
main = "./src/prod.ts"
compatibility_date = "2023-03-14"
routes = [
    { pattern = "dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [
    { binding = "TEST_STRAPI_UPDATES", id = "3a904bf6d19b4d8ba0e3ed44bb2cdca7" },
]

[env.development]
name = "dilmahtea-me-dimass-dev"
main = "./src/dev.ts"
workers_dev = true
routes = [
    { pattern = "dev.dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]


[vars]
# DIMASS_APIKEY
# DIMASS_SIGNATURE
# STRAPI_APIKEY
