name = "dilmahtea-me-dimass"
main = "./src/prod.ts"
compatibility_date = "2023-03-14"
routes = [
    { pattern = "dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [
    { binding = "TEST_STRAPI_UPDATES", id = "3a904bf6d19b4d8ba0e3ed44bb2cdca7", preview_id = "81b48c740dda4db0ae4bbd1e215fbb01" },
]

[env.development]
name = "dilmahtea-me-dimass-dev"
main = "./src/dev.ts"
workers_dev = true
routes = [
    { pattern = "dev.dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]


[vars]
STRAPI_URL = "https://cms.dilmahtea.me/api"
DIMASS_URL = "https://www.supportplaza.nl/papi/stock/1.0"

# The necessary secrets are:
# - DIMASS_APIKEY
# - DIMASS_SIGNATURE
# - STRAPI_APIKEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
