name = "dilmahtea-me-dimass-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = false
logpush=true
routes = [
    { pattern = "dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [
    { binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" },
]

[env.development]
name = "dilmahtea-me-dimass-webhook-dev"
routes = [
    { pattern = "dev.dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [
    { binding = "EXACT_TOKENS", id = "194d0b00ac24422bb728e326bb43480c" },
]

# secrets
# STRAPI_APIKEY
# STRAPI_GRAPHQL_ENDPOINT
# DIMASS_APIKEY
# DIMASS_SECRET
# DIMASS_API_ENDPOINT
# DIMASS_WEBHOOK_SECRET
