name = "dilmahtea-me-dimass"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = true
routes = [
    { pattern = "dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
[vars]
STRAPI_API_ENDPOINT = "https://cms.dilmahtea.me/api"
STRAPI_GRAPHQL_ENDPOINT = "https://cms.dilmahtea.me/graphql"
DIMASS_API_ENDPOINT = "https://www.supportplaza.nl/papi/stock/1.0"

[env.development]
name = "dilmahtea-me-dimass-dev"
routes = [
    { pattern = "dev.dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
[vars]
STRAPI_API_ENDPOINT = "https://cms.dilmahtea.me/api"
STRAPI_GRAPHQL_ENDPOINT = "https://cms.dilmahtea.me/graphql"
DIMASS_API_ENDPOINT = "https://www.supportplaza.nl/papi/stock/1.0"

# The necessary secrets are:
# - DIMASS_APIKEY
# - DIMASS_SIGNATURE
# - STRAPI_APIKEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
