name = "dilmahtea-me-dimass"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = true
routes = [
    { pattern = "dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]

[env.development]
name = "dilmahtea-me-dimass-dev"
routes = [
    { pattern = "dev.dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]

[vars]
STRAPI_URL = "https://cms.dilmahtea.me/api"
DIMASS_URL = "https://www.supportplaza.nl/papi/stock/1.0"

# The necessary secrets are:
# - DIMASS_APIKEY
# - DIMASS_SIGNATURE
# - STRAPI_APIKEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
