name = "dilmahtea-me-dimass-webhook"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = false
logpush = true
placement = { mode = "smart" }
vars = { ENVIRONMENT = "PRODUCTION", JOURNAL_CODE = "VER" }
routes = [
    { pattern = "dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [
    { binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" },
    { binding = "EXACT_LAYOUTS", id = "b75eb1bee9d7488fa33b8be89caab307" },
    { binding = "WORKER_CONTEXTS", id = "3fcd1790b1e644caa0d76d1be2fc27f7" }
]

[env.development]
name = "dilmahtea-me-dimass-webhook-dev"
vars = { ENVIRONMENT = "DEVELOPMENT", JOURNAL_CODE = "VER" }
routes = [
    { pattern = "dev.dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [
    { binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" },
    { binding = "EXACT_LAYOUTS", id = "f767fadbe91d459893e903cc9a01d40a" },
    { binding = "WORKER_CONTEXTS", id = "710872f91ae946d987a38af244352718" }
]

# secrets
# DIMASS_API_KEY
# DIMASS_API_SECRET
# DIMASS_API_ENDPOINT
# DIMASS_TEMP_WEBHOOK_SECRET
# DKIM_PRIVATE_KEY
# EXACT_API_ENDPOINT
# STRAPI_ACCESS_TOKEN
# STRAPI_GRAPHQL_ENDPOINT
# DIMASS_WEBHOOK_SECRET
