name = "dilmahtea-me-dimass"
main = "./src/prod.ts"
compatibility_date = "2023-03-14"
routes = [
    { pattern = "dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [{ binding = "DIMASS_WEBHOOK_RESPONSES", id = "ae8c205257e54cd6b2cac4a2888d2f45" }]

[env.development]
name = "dilmahtea-me-dimass-dev"
main = "./src/dev.ts"
workers_dev = true
routes = [
    { pattern = "dev.dimass-webhook.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [{ binding = "DIMASS_WEBHOOK_RESPONSES", id = "ae8c205257e54cd6b2cac4a2888d2f45" }]


[vars]
# DIMASS_APIKEY
# DIMASS_SIGNATURE
# STRAPI_APIKEY