name = "dilmahtea-me-plausible"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.js"
workers_dev = true
logpush=true

routes = [
    { pattern = "analytics.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]

# [env.development]
# name = "dilmahtea-me-plausible-dev"
# routes = [
#     { pattern = "dev.analytics-stats.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
# ]
