name = "dilmahtea-me-email"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-06-08"
main = "./src/prod.js"
workers_dev = false
routes = [
    { pattern = "crowdfunding-mail.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [{ binding = "MAILS", id = "51f5be62eaf64aa8a9c69bccb81d396e" }]
services = [
    { binding = "VALIDATOR", service = "dilmahtea-me-validator", environment = "production" },
]

[env.development]
name = "dilmahtea-me-email-dev"
main = "./src/dev.js"
routes = [
    { pattern = "dev.crowdfunding-mail.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" }
]
kv_namespaces = [{ binding = "MAILS", id = "51f5be62eaf64aa8a9c69bccb81d396e" }]
services = [
    { binding = "VALIDATOR", service = "dilmahtea-me-validator-dev", environment = "production" },
]