name = "dilmahtea-me-email"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = false
logpush = true
placement = { mode = "smart" }
routes = [
    { pattern = "email.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
d1_databases = [
    { binding = "USERS", database_name = "users", database_id = "74a1dc02-0705-44fb-b009-fb2fe974e098" }
]
services = [{ binding = "RETRY_WORKERS", service = "dilmahtea-me-retry-workers" }]

# secrets
# DKIM_PRIVATE_KEY
# CF_SECURE_WORKER_TOKEN