name = "dilmahtea-me-exact-account"
account_id = "f0f636c746c8673c3905e9104b385251"
compatibility_date = "2022-11-30"
main = "./src/index.ts"
workers_dev = false
logpush = true
placement = { mode = "smart" }
routes = [
    { pattern = "exact-account.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [
    { binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" },
    { binding = "EXACT_GUID_COLLECTION", id = "b75eb1bee9d7488fa33b8be89caab307" },
]
d1_databases = [
    { binding = "USERS", database_name = "users", database_id = "74a1dc02-0705-44fb-b009-fb2fe974e098" }
]
services = [{ binding = "RETRY_WORKERS", service = "dilmahtea-me-retry-workers" }]

[env.development]
name = "dilmahtea-me-exact-account-dev"
routes = [
    { pattern = "dev.exact-account.scripts.dilmahtea.me", custom_domain = true, zone_name = "dilmahtea.me" },
]
kv_namespaces = [
    { binding = "EXACT_TOKENS", id = "0cbeb7b84a6a4e31b9c3360f97c9cef5" },
    { binding = "EXACT_GUID_COLLECTION", id = "f767fadbe91d459893e903cc9a01d40a" },
]
d1_databases = [
    { binding = "USERS", database_name = "users_dev", database_id = "076751ed-7610-4965-b72d-e9d619227957" }
]
services = [{ binding = "RETRY_WORKERS", service = "dilmahtea-me-retry-workers" }]

# secrets
# DKIM_PRIVATE_KEY
# EXACT_API_ENDPOINT
# CF_SECURE_WORKER_TOKEN