name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main

env:
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_SIGNING_KEY: ${{ secrets.STRIPE_SIGNING_KEY }}

jobs:
  deploy:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2

      - name: Publish Form Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "packages/dilmahtea-me-form"

      - name: Publish Email Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "packages/dilmahtea-me-email"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Stripe Dependencies
        run: npm install
        with:
          workingDirectory: "packages/dilmahtea-me-stripe"

      - name: Install Stripe WebHook Dependencies
        run: npm install
        with:
          workingDirectory: "packages/dilmahtea-me-stripe-webhook"

      - name: Publish Stripe Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "packages/dilmahtea-me-stripe"

      - name: Publish Stripe Webhook Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "packages/dilmahtea-me-stripe-webhook"
