name: Deploy Cloudflare Workers

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to Cloudflare Workers
        shell: bash
        run: |
          for worker_src in src/workers/*; do git diff ${{ github.event.before }} HEAD -- $worker_src |& (grep -q . && cd $worker_src && pnpm wrangler deploy${{ github.ref == 'refs/heads/dev' && ' --env=development' || '' }}) & done; wait
