name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main

env:
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_SIGNING_KEY: ${{ secrets.STRIPE_SIGNING_KEY }}

jobs:
  deploy:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Publish Baserow Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-baserow"

      - name: Publish Baserow Worker (Development)
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-baserow"
          command: "publish --env development"

      - name: Publish Baserow Stats Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-baserow"

      - name: Publish Baserow Stats Worker (Development)
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-baserow"
          command: "publish --env development"

      - name: Publish Crowdfunding Mail Store Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-crowdfunding-mail-store"

      - name: Publish Crowdfunding Mail Store Worker (Development)
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-baserow"
          command: "publish --env development"

      - name: Publish Email Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-email"

      - name: Publish Email Worker (Development)
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-email"
          command: "publish --env development"

      - name: Publish Stats Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "src/workers/dilmahtea-me-stats"

      - name: Publish Stripe Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npm install
          workingDirectory: "src/workers/dilmahtea-me-stripe"

      - name: Publish Stripe Worker (Development)
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npm install
          workingDirectory: "src/workers/dilmahtea-me-stripe"
          command: "publish --env development"

      - name: Publish Stripe Webhook Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npm install
          workingDirectory: "src/workers/dilmahtea-me-stripe-webhook"

      - name: Publish Stripe Webhook Worker (Development)
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npm install
          workingDirectory: "src/workers/dilmahtea-me-stripe-webhook"
          command: "publish --env development"

      - name: Publish Validator Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npx pnpm install
          workingDirectory: "src/workers/dilmahtea-me-validator"

      - name: Publish Validator Worker (Development)
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npx pnpm install
          workingDirectory: "src/workers/dilmahtea-me-validator"
          command: "publish --env development"
